### ISSUE TITLE
How it works

### ISSUE THREAD

**Issue by DanySpin97** [DanySpin97/tt#4]
# Services
tt has its own set of services, which match (to a certain degree) to [s6 format](https://skarnet.org/software/s6/servicedir.html) format. Additional options will be added according to #2.

## Service directories
- `/usr/share/tt/services/` for services installed at a system level
- `/etc/tt/services/` for services installed by the administrator of the system
- `$XDG_CONFIG_DIR/tt/services` for user installed services

## Services names
The name of the services will match the one of the underlayng programs called and the file.
E.g. sndiod daemon will have service sndiod saved in `/usr/share/tt/services/sndiod.system`.

Services will have suffix `.system` or `.user` based on which user can enable the service.
`.system` can only be enabled by root but they change the user running the program to any available in the system.
 
## Parser
The service format choosed is similar to the INI format but since the INI parser are not capable of parsing multiline strings without using escape characters, an ad-hoc parser is needed.

Impl. detail: The parser objects havo to be reentrant so that multile services can be parser in parallel (one service per thread).

## Administration
It shall be possible to administrate the services on a system by using a CLI interface (see #1 for more details about the interface needed). The following features should be provided:

- Enabling/disabling a service
- Starting/stopping a service
- Quering the status of the system
- Quering and changing the config of a service

### Enabling
After tt services have been parsed, most of the time they will be enabled (scheduled by the user to run on the next boot). To enable a service, it needs to be converted into s6-rc format and then a new database should be compiled.

### Conversion to s6-rc format
tt use the s6 suite to run the programs. Therefore tt services shall be converted into the s6-rc format. This phase is needed only when enabling a service. The folder where the converted services shall be stored is `/var/lib/tt/services` (except for bootstrap services).

### Compilation of s6-rc services
A set of s6-rc services is not ready to be used yet: it needs to be compiled into a database of services by s6-rc-compile. This result into a folder `/var/lib/tt/db` (except for bootstrap services).

### [Scan directory](https://skarnet.org/software/s6/scandir.html)
Using [s6-svscan](https://skarnet.org/software/s6/s6-svscan.html) and by copying the appropriate database folders, the services will be started.

## tt services configuration
The services should be configurable by exposing environment variables to the sysadmin/user running its services. The most common configuration is about the CLI arguments passed to the underlaying programs. E.g. telling sndio to use a different sample rate by adding `-r 192000`.

These environment variables are defined in the service file (along with a sane default). When the service is started/stopped, these variables will be read `/etc/tt/conf` for the system services and from `$XDG_CONFIG_DIR`/tt/conf` for user services.

## Logging
Log files for tt are regular text files and are saved in `/var/log/tt`.

- For oneshot the log will be the same as the s6-svscan directory, so this one needs to be redirected to `/var/log/tt`.
- For longrun the log is directly written into `/var/log/tt`, thanks to the s6-rc pipeline and to the s6-log program (which needs to be changed in the future).

# Boot
tt-boot cli will provide the booting program for a system (`/bin/init`). This program will correctly setup and redirect the stdin/stdout to log the booting process and then call stage1 script phase. Default scripts for the various stages will be provided in a different repository (along with boostrap services) so tt only provides policy.

## Bootstrap services
Making the system read-write and mounting partitions according to /etc/fstab is usually the duty of the boot services. Since it will be too cumbersome to add these services as a dependency in all the other system services, tt will provide the possibility to run "bootstrap" services. A default set of bootstrap services will be provided in a different repository.

# Bonus: tt-nice-boot

**Comment by Cogitri** [comment]
Just a few misc things I want to note now - we don't have to work on those right now, but I felt like they're worth noting.

* User Services:
    * Is it possible for distros to install .user services to `/usr/share/tt/services`? That'd be useful to avoid horrific stuff similar to this: https://gitlab.alpinelinux.org/alpine/aports/merge_requests/1907/diffs#56170e5f90ecb6515d4769ab49c31c4e42550d70_0_19 (GNUNet apparently needs processes running as both GNUNet user and via the user using that particular GNUNet instance). It's super bad/impossible to implement this cleanly in OpenRC.
* Services configuration:
    * Do I understand correctly that all additional configuration is done in the same file? Doesn't that make it probable to accidentally cause conflicts between environment variables (e.g. by having a `CMD_ARGS` env variable for two services)? I mean it is easy to avoid this by prefixing the environment variables with the service name, but I think I'd prefer if it wasn't possible to have conflicts at all.

**Comment by DanySpin97** [comment]
> Is it possible for distros to install .user services to /usr/share/tt/services

Yea, both services (`.user`, `.system`) can get installed there.

> Do I understand correctly that all additional configuration is done in the same file?

That wasn't clearly explained. For each service there will be a corresponding configuration file in `/etc/tt/conf` that will have the default environment written in the service file (and it's modifiable). The conflicts will happen when a new version of the service (with a different default environment) will be enabled but this can be made to work.

The config was shared between the various script, i.e. `start` and `stop` script in a one environment, which resulted in something like this in 66:

```
[start]
execute = ( /foo/bar ${CMD_ARGS_START} )

[stop]
execute = ( /foo/bar ${CMD_ARGS_STOP} )

[environment]
CMD_ARGS_START="-n"
CMD_ARGS_STOP="-p"
```

This is suboptimal. I thought of having something like this:

```
[config]
MYENV=foo

[config:start]
CMD_ARGS="-n"

[config:stop]
CMD_ARGS="-p"
```

This is optimal from a service writing point of view but /etc/tt/conf/<myservice> would not be a 1:1 match anymore. The disadvantage of this approach is that the users can only change the configuration using tt command line.

**Comment by Cogitri** [comment]
> This is suboptimal. I thought of having something like this:

Hm, I don't think there are many services which terminate just by having different arguments passed to them and IMHO it makes things a bit less clear (since one environment variable can have different values depending on when you look at it) compared to having a CMD_ARGS_START and CMD_ARGS_STOP (I don't suspect this happens often anyway)

**Comment by DanySpin97** [comment]
> Hm, I don't think there are many services

Potentially all the oneshots, but I agree it would make things less clear. Let's keep it simple then!
